# Generated by Django 3.0.3 on 2020-10-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagel_site', '0002_auto_20201014_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bagel_bucks',
            field=models.FloatField(default=100),
        ),
    ]
