# Generated by Django 3.0.3 on 2020-10-20 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagel_site', '0007_lineitem_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='associated_line_item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='bagel_site.LineItem'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='menu_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bagel_site.MenuItem'),
        ),
    ]
