# Generated by Django 3.0.3 on 2020-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagel_site', '0009_auto_20201020_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.CharField(default='', max_length=40),
        ),
    ]
