# Generated by Django 3.0.3 on 2020-10-25 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagel_site', '0010_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='associated_line_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bagel_site.LineItem'),
        ),
    ]
