# Generated by Django 3.0.3 on 2020-10-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagel_site', '0014_menuitem_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='associated_line_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitem', to='bagel_site.LineItem'),
        ),
    ]
